
#General settings
[General]
	#Dimension to use for weather displayed on the 'Join Multiplayer' screen.
	dimName = "minecraft:overworld"

#Feature settings
[Feature]
	#Should we show the Date? [True/False]
	enableDate = true
	#Should we show the Season? [True/False]
	enableSeasons = false
	#Should we show the Weather? [True/False]
	enableWeather = true
	#Should we show the Time? [True/False]
	enableTime = true

#Display settings
[Display]
	#What should we show as the Afternoon text?
	labelAfternoon = " PM"
	#What should we show as the Time text?
	labelTime = "Time: "
	#What should we show as the Thundering text?
	labelThundering = "Thundering"
	#What should we show as the Morning text?
	labelMorning = " AM"
	#What should we show as the Raining text?
	labelRaining = "Rain"
	#What should we show as the Season text?
	labelSeason = "Season: "
	#What should we show as the Fall text?
	labelFall = "Fall"
	#What should we show as the Years text?
	labelYears = "y "
	#What should we show as the Winter text?
	labelWinter = "Winter"
	#What should we show as the Day text?
	labelDays = "d"
	#What should we show as the Clear text?
	labelClear = "Clear"
	#What should we show as the Weather text?
	labelWeather = "Weather: "
	#What should we show as the Spring text?
	labelSpring = "Spring"
	#What should we show as the Summer text?
	labelSummer = "Summer"
	#What should we show as the Date text?
	labelDate = "Current Day: "

